# Generated by Django 6.0.6 on 2026-06-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0003_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order', 'Order'), ('consultation', 'Consultation'), ('message', 'Message'), ('user', 'User'), ('stock', 'Stock')], default='order', max_length=30),
        ),
    ]
